name: travel_app_youtube
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  responsive_sizer: ^3.3.1
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  provider: ^6.1.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.3.0
  stroke_text: ^1.0.0
  scaffold_plus: ^1.0.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/data/
    - assets/audio/
    - assets/svg/

  fonts:
    - family: display
      fonts:
        - asset: assets/fonts/display.otf
